import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";
import { UserProvider } from "./_context/userContext";

export const metadata: Metadata = {
  title: "RTB House Home Task",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="bg-slate-500 py-5 text-white">
          <Link className="font-sans text-l font-bold px-4 py-2 mx-2 border rounded-lg hover:bg-slate-600 hover:shadow-md active:bg-slate-700 active:shadow-lg" href="/">Main page</Link>
          <Link className="font-sans text-l font-bold px-4 py-2 mx-2 border rounded-lg hover:bg-slate-600 hover:shadow-md active:bg-slate-700 active:shadow-lg" href="/dashboard">Dashbaord</Link>
        </div>
        <div className="container mx-auto p-4">
          <UserProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
