import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";
import { UserProvider } from "./_context/userContext";

export const metadata: Metadata = {
  title: "RTB House Home Task",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div>
          <Link href="/">Home</Link>
          <Link href="/dashboard">Dashbaord</Link>
        </div>
        <UserProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </UserProvider>
      </body>
    </html>
  );
}
